kind: pipeline
type: docker
name: globescene-admin-iview

steps:
- name: npm-build
  image: node
  environment:
    NODE_ENV: production
  commands:
    - npm install
    - npm run build

  volumes:
    - name: cache
      path: /globescene-admin-iview

volumes:
  - name: cache
    temp: {}
